Repository ubco-db/EmbedDB, pull requests merged in 2024-05, with the labels that each got.

#33 Add default constructor
  lib/EmbedDB-Utility/embedDBUtility.c
  lib/EmbedDB-Utility/embedDBUtility.h
Labels: Port

#61 Port Amalgamation Code to EmbedDB
  .github/workflows/amalgamate.yml
  .github/workflows/remote.yml
  .github/workflows/run_python_tests.yml
  .gitignore
  amalgamation/__init__.py
  amalgamation/amalgamation.py
  amalgamation/tests/__init__.py
  amalgamation/tests/test_directed_graph.py
  amalgamation/tests/test_file_cleaning.py
  amalgamation/tests/test_file_handlers.py
  amalgamation/tests/test_files/hello-world.txt
  amalgamation/tests/test_files/only-include-duplicate.c
  amalgamation/tests/test_files/only-include-inline-comments.c
  amalgamation/tests/test_files/only-include.c
  amalgamation/tests/test_helper_functions.py
  distribution/embedDB.c
  distribution/embedDB.h
  scripts/replacementScript.py
  src/embedDB/embedDB.c
Labels: enhancement, ci, Port

#68 Fix Amalgamation Process to Be Deterministic
  amalgamation/amalgamation.py
Labels: bug

#70 Updated Github Action to Open PR When Changes Detected on Distribution Files
  .github/workflows/amalgamate.yml
  amalgamation/amalgamation.py
Labels: bug, enhancement
